"""add task.plase

Revision ID: 3f4ca0b2a2d3
Revises: 3c4f04d05230
Create Date: 2023-04-13 18:00:02.950429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f4ca0b2a2d3'
down_revision = '3c4f04d05230'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remind')
    op.add_column('task', sa.Column('place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'place')
    op.create_table('remind',
    sa.Column('dtime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connector', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='remind_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remind_pkey')
    )
    # ### end Alembic commands ###
