"""init commit

Revision ID: 67ef6db8a2ab
Revises:
Create Date: 2023-03-20 16:05:50.979998
"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '67ef6db8a2ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'task',
        sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'description', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_task_description'), 'task', ['description'], unique=False
    )
    op.create_index(op.f('ix_task_user'), 'task', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_user'), table_name='task')
    op.drop_index(op.f('ix_task_description'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
