"""update User

Revision ID: 96265422d15e
Revises: d63ecde3a2f5
Create Date: 2023-04-13 10:34:33.843329

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '96265422d15e'
down_revision = 'd63ecde3a2f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_phone', table_name='user')
    op.drop_index('ix_user_tg', table_name='user')
    op.create_index(op.f('ix_user_tg'), 'user', ['tg'], unique=True)
    op.drop_index('ix_user_vk', table_name='user')
    op.create_index(op.f('ix_user_vk'), 'user', ['vk'], unique=True)
    op.drop_column('user', 'name')
    op.drop_column('user', 'phone')
    op.alter_column('userdata', 'core_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('userdata', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('userdata', 'core_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_vk'), table_name='user')
    op.create_index('ix_user_vk', 'user', ['vk'], unique=False)
    op.drop_index(op.f('ix_user_tg'), table_name='user')
    op.create_index('ix_user_tg', 'user', ['tg'], unique=False)
    op.create_index('ix_user_phone', 'user', ['phone'], unique=False)
    # ### end Alembic commands ###
