"""fix dtime

Revision ID: c745d88db3fb
Revises: 67ef6db8a2ab
Create Date: 2023-03-20 17:49:10.407774

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c745d88db3fb'
down_revision = '67ef6db8a2ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('dtime', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'dtime')
    # ### end Alembic commands ###
