"""new models UserData

Revision ID: d63ecde3a2f5
Revises: dc4ea0ee1959
Create Date: 2023-04-12 11:08:37.826372

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd63ecde3a2f5'
down_revision = 'dc4ea0ee1959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('tg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_tg'), 'user', ['tg'], unique=False)
    op.create_index(op.f('ix_user_vk'), 'user', ['vk'], unique=False)
    op.create_table('task',
    sa.Column('dtime', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_description'), 'task', ['description'], unique=False)
    op.create_table('userdata',
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('core_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdata')
    op.drop_index(op.f('ix_task_description'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_user_vk'), table_name='user')
    op.drop_index(op.f('ix_user_tg'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
