"""add Schedule model

Revision ID: a782de47d4d5
Revises: c745d88db3fb
Create Date: 2023-03-27 17:06:53.006867

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a782de47d4d5'
down_revision = 'c745d88db3fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
